spring:
  application:
    name: equipamentos-raros
  mail:
    host: ${EMAIL_HOST}
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration
    validate-on-migrate: true
    baseline-on-migrate: true
    user: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

springdoc:
  api-docs:
    path: /v3/api-docs
    #    enabled: false
    version: openapi_3_0
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    filter: true
    tagsSorter: alpha
    operationsSorter: method
    doc-expansion: none

feign:
  client:
    default:
      connectiimeout: 5000
      readtimeout: 5000
      LoggerLevel: basic
  viaCep:
    url: https://viacep.com.br/ws
