CREATE TABLE equipment_collaborator (
     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    collaborator_id BIGINT NOT NULL,
    equipment_id BIGINT NOT NULL,
    delivery_date DATE NOT NULL,
    return_date DATE,
    delivery_status VARCHAR(255),
    notes TEXT
);