CREATE TABLE equipment_collaborator
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    collaborator_id         BIGINT NOT NULL,
    equipment_id            BIGINT NOT NULL,
    delivery_date           DATE   NOT NULL,
    prevision_delivery_date DATE,
    return_date             DATE,
    delivery_status         VARCHAR(255),
    notes                   TEXT,

    CONSTRAINT fk_equipment_collaborator_collaborator
        FOREIGN KEY (collaborator_id)
            REFERENCES collaborators (id)
            ON DELETE CASCADE,

    CONSTRAINT fk_equipment_collaborator_equipment
        FOREIGN KEY (equipment_id)
            REFERENCES equipments (id)
            ON DELETE CASCADE
);