CREATE TABLE equipment_return
(
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    delivery_date             DATE         NOT NULL,
    receipt_date              DATE,
    status                    VARCHAR(255) NOT NULL,
    note                      TEXT,
    equipment_collaborator_id BIGINT       NOT NULL UNIQUE,

    CONSTRAINT fk_equipment_return_equipment_collaborator
        FOREIGN KEY (equipment_collaborator_id)
            REFERENCES equipment_collaborator (id)
            ON DELETE CASCADE
);