CREATE TABLE retornos_previstos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    expected_return_date DATE NOT NULL,
    equipment_collaborator_id BIGINT NOT NULL UNIQUE,

    CONSTRAINT fk_retornos_previstos_equipment_collaborator
        FOREIGN KEY (equipment_collaborator_id)
        REFERENCES equipment_collaborator(id)
        ON DELETE CASCADE
);