CREATE TABLE equipment_purchases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    equipment_type VARCHAR(100) NOT NULL,
    quantity INT NOT NULL,
    order_date DATE NOT NULL,
    supplier VARCHAR(100) NOT NULL,
    receipt_date DATE NULL
);