CREATE TABLE users
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(100) NOT NULL,
    email           VARCHAR(50) NOT NULL UNIQUE,
    password        VARCHAR(50) NOT NULL,
    email_confirmed BOOLEAN DEFAULT FALSE
);