CREATE TABLE expected_hirings
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    expected_hire_date     DATE         NOT NULL,
    position               VARCHAR(100) NOT NULL,
    equipment_requirements VARCHAR(255) NOT NULL,
    region                 VARCHAR(255) NOT NULL
);