CREATE TABLE collaborators
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                VARCHAR(255)        NOT NULL,
    cpf                 VARCHAR(14) UNIQUE  NOT NULL,
    email               VARCHAR(255) UNIQUE NOT NULL,
    phone               VARCHAR(20),
    address_id          BIGINT,
    contract_start_date DATE                NOT NULL,
    contract_end_date   DATE
);