CREATE TABLE equipments (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type VARCHAR(100) NOT NULL,
    serial_number VARCHAR(100) NOT NULL UNIQUE,
    brand VARCHAR(100) NOT NULL,
    model VARCHAR(100) NOT NULL,
    specs TEXT,
    acquisition_date DATE NOT NULL,
    usage_time_months INTEGER NOT NULL,
    status VARCHAR(50) NOT NULL
);
