CREATE TABLE stock_parameters (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    equipment_type VARCHAR(255) NOT NULL,
    min_stock INTEGER NOT NULL,
    avg_restock_time_days INTEGER NOT NULL,
    avg_stock_consumption_time_days INTEGER NOT NULL,
    avg_delivery_time_days INTEGER NOT NULL,
    avg_defective_rate FLOAT NOT NULL
);
