CREATE TABLE stock
(
    id                              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    equipment_type                  VARCHAR(21) NOT NULL,
    current_stock                   INT         NOT NULL DEFAULT 0,
    min_stock                       INTEGER              DEFAULT NULL,
    security_stock                  INT                  DEFAULT NULL,
    avg_restock_time_days           INTEGER              DEFAULT NULL,
    avg_stock_consumption_time_days INTEGER              DEFAULT NULL,
    avg_defective_rate              FLOAT                DEFAULT NULL
);