CREATE TABLE stock_alerts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stock_id BIGINT NOT NULL,
    alert_sent_at TIMESTAMP NOT NULL,
    stock_alert_status VARCHAR(10),

    CONSTRAINT fk_stock_alerts_stock
        FOREIGN KEY (stock_id)
        REFERENCES stock(id)
        ON DELETE CASCADE
);