CREATE TABLE equipments_stock (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    equipment_type VARCHAR(29) NOT NULL UNIQUE,
    current_stock INT NOT NULL
);

CREATE TABLE stock_alerts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    equipment_stock_id BIGINT NOT NULL,
    minimum_stock INT NOT NULL,
    security_stock INT NOT NULL,
    alert_sent_at TIMESTAMP NOT NULL,
    stock_alert_status VARCHAR(10),

    CONSTRAINT fk_stock_alert_equipment
        FOREIGN KEY (equipment_stock_id)
        REFERENCES equipments_stock(id)
        ON DELETE CASCADE
);